<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="Tareq" failures="1" tests="5" name="Personal loan" time="0.068" errors="0" timestamp="2023-09-12T02:16:44 EDT">
  <testcase classname="test.day1" name="Demo" time="0.017">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at test.day1.Demo(day1.java:23)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- Demo -->
  <testcase classname="test.day2" name="ploan" time="0.002"/>
  <testcase classname="test.day4" name="LoginAPIHomeLoan" time="0.001"/>
  <testcase classname="test.day4" name="MobileLoginHomeLoan" time="0.002"/>
  <testcase classname="test.day4" name="WebloginHomeLoan" time="0.001"/>
  <testcase classname="test.day1" name="SecondTest" time="0.0">
    <ignored/>
  </testcase> <!-- SecondTest -->
</testsuite> <!-- Personal loan -->
